### PR TITLE
Fix error

### PR DESCRIPTION
**Pull request by maresb**

### CODE REVIEW

**Comment by maresb** [comment]
Hmm, did I get the wrong base??? :slightly_frowning_face:

**Comment by maresb** [comment]
@bollwyvl, does this look good? There were a few errors in the CI run for https://github.com/conda-incubator/conda-lock/pull/298, but I suspect that they're only sporadic.

**Comment by bollwyvl** [comment]
I'm away from keyboard, so feel free to push to my main pr, but in
principle this looks good: perhaps we advertise `conda-lock[git_support]`,
so that eventually a non-vulnerable lower bound can be set? Then we could
do multi-output for conda-forge, and get pip_support in there, too, with
the relatively sensitive poetry pin (if that's still even accurate with the
vendoring)

**Comment by maresb** [comment]
also Afk ... I suspect you need to rebase. I am not full maintainer so cannot commit to your branch

**Comment by maresb** [comment]
> I suspect you need to rebase.

I was mistaken. Your `main` branch is behind, but this branch is up-to-date.

>  and get pip_support in there, too

Thank you for mentioning this! After vendoring Poetry in #240 I forgot to deprecate `pip_support`. Adding it to my todos with #299.

> Then we could do multi-output for conda-forge

I'd personally like to avoid this if possible, since it makes the recipe complicated. Adding Git metadata is not default, so it seems more like a rare edge case to me. And with a loud and clear error message telling people to install GitPython, it seems to me like there's little room for confusion. What do you think?

**Pull request merged**
